# This is a basic workflow to help you get started with Actions
name: Deploy to AWS Lambda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "workflow"
  workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2 # Seoul

    if: github.repository_owner == 'thkim0022'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Install Python Packages
      - name: Install Python Packages
        working-directory: ./
        run: |
          mkdir packages
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t packages/

      # Make a Zip File
      - name: Make a Zip File
        working-directory: ./
        run: zip -r ${{ github.event.repository.name }}.zip .

      # Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        working-directory: ./
        run: |
          aws lambda update-function-code \
          --function-name ${{ github.event.repository.name }} \
          --zip-file fileb://${{ github.event.repository.name }}.zip \
          --publish > lam_conf.json

      # Update a Lambda Configuration for SQS
      - name: Update a Lambda Configuration for SQS
        working-directory: ./
        run: |
          lambda_arn=$(cat lam_conf.json | jq -r '.FunctionArn');
          echo "lambda_arn: $lambda_arn";
          aws lambda update-event-source-mapping \
          --uuid ${{ secrets.AWS_SQS_UUID }} \
          --function-name $lambda_arn
